"""add message field to collaborations and change default to pending

Revision ID: 378380407ebd
Revises: 9b474000f57b
Create Date: 2026-05-09 18:14:16.684180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378380407ebd'
down_revision = '9b474000f57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
